// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.2.5
//   protoc               v5.28.2
// source: general.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "general";

export enum TimeSlot {
  SLOT_10_12 = 0,
  SLOT_12_14 = 1,
  SLOT_14_16 = 2,
  SLOT_16_18 = 3,
  SLOT_18_20 = 4,
  SLOT_20_22 = 5,
  SLOT_22_00 = 6,
  UNRECOGNIZED = -1,
}

export function timeSlotFromJSON(object: any): TimeSlot {
  switch (object) {
    case 0:
    case "SLOT_10_12":
      return TimeSlot.SLOT_10_12;
    case 1:
    case "SLOT_12_14":
      return TimeSlot.SLOT_12_14;
    case 2:
    case "SLOT_14_16":
      return TimeSlot.SLOT_14_16;
    case 3:
    case "SLOT_16_18":
      return TimeSlot.SLOT_16_18;
    case 4:
    case "SLOT_18_20":
      return TimeSlot.SLOT_18_20;
    case 5:
    case "SLOT_20_22":
      return TimeSlot.SLOT_20_22;
    case 6:
    case "SLOT_22_00":
      return TimeSlot.SLOT_22_00;
    case -1:
    case "UNRECOGNIZED":
    default:
      return TimeSlot.UNRECOGNIZED;
  }
}

export function timeSlotToJSON(object: TimeSlot): string {
  switch (object) {
    case TimeSlot.SLOT_10_12:
      return "SLOT_10_12";
    case TimeSlot.SLOT_12_14:
      return "SLOT_12_14";
    case TimeSlot.SLOT_14_16:
      return "SLOT_14_16";
    case TimeSlot.SLOT_16_18:
      return "SLOT_16_18";
    case TimeSlot.SLOT_18_20:
      return "SLOT_18_20";
    case TimeSlot.SLOT_20_22:
      return "SLOT_20_22";
    case TimeSlot.SLOT_22_00:
      return "SLOT_22_00";
    case TimeSlot.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum UserType {
  CUSTOMER = 0,
  MANAGER = 1,
  UNRECOGNIZED = -1,
}

export function userTypeFromJSON(object: any): UserType {
  switch (object) {
    case 0:
    case "CUSTOMER":
      return UserType.CUSTOMER;
    case 1:
    case "MANAGER":
      return UserType.MANAGER;
    case -1:
    case "UNRECOGNIZED":
    default:
      return UserType.UNRECOGNIZED;
  }
}

export function userTypeToJSON(object: UserType): string {
  switch (object) {
    case UserType.CUSTOMER:
      return "CUSTOMER";
    case UserType.MANAGER:
      return "MANAGER";
    case UserType.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface Error {
  errors: string[];
}

export interface ResponseStatus {
  code: number;
  error?: Error | undefined;
}

export interface EmptyResponse {
  status: ResponseStatus | undefined;
}

export interface ByIdRequest {
  id: string;
}

export interface EmptyRequest {
}

export interface PaginateRequest {
  page: number;
  perPage: number;
  fulltextSearch?: string | undefined;
}

export interface PaginationMetaResult {
  recordsTotal: number;
  recordsFiltered: number;
}

export interface UserDto {
  id: string;
  username: string;
  age: number;
  type: UserType;
}

export interface Ticket {
  id: string;
  ticketNumber: number;
  user?: UserDto | undefined;
  session: SessionDto | undefined;
}

export interface SessionDto {
  id: string;
  date: string;
  timeSlot: TimeSlot;
  roomNumber: number;
  tickets: Ticket[];
}

function createBaseError(): Error {
  return { errors: [] };
}

export const Error: MessageFns<Error> = {
  encode(message: Error, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.errors) {
      writer.uint32(10).string(v!);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Error {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseError();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.errors.push(reader.string());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Error {
    return {
      errors: globalThis.Array.isArray(object?.errors) ? object.errors.map((e: any) => globalThis.String(e)) : [],
    };
  },

  toJSON(message: Error): unknown {
    const obj: any = {};
    if (message.errors?.length) {
      obj.errors = message.errors;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Error>, I>>(base?: I): Error {
    return Error.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Error>, I>>(object: I): Error {
    const message = createBaseError();
    message.errors = object.errors?.map((e) => e) || [];
    return message;
  },
};

function createBaseResponseStatus(): ResponseStatus {
  return { code: 0, error: undefined };
}

export const ResponseStatus: MessageFns<ResponseStatus> = {
  encode(message: ResponseStatus, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.code !== 0) {
      writer.uint32(8).int32(message.code);
    }
    if (message.error !== undefined) {
      Error.encode(message.error, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ResponseStatus {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseResponseStatus();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.code = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.error = Error.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ResponseStatus {
    return {
      code: isSet(object.code) ? globalThis.Number(object.code) : 0,
      error: isSet(object.error) ? Error.fromJSON(object.error) : undefined,
    };
  },

  toJSON(message: ResponseStatus): unknown {
    const obj: any = {};
    if (message.code !== 0) {
      obj.code = Math.round(message.code);
    }
    if (message.error !== undefined) {
      obj.error = Error.toJSON(message.error);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ResponseStatus>, I>>(base?: I): ResponseStatus {
    return ResponseStatus.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ResponseStatus>, I>>(object: I): ResponseStatus {
    const message = createBaseResponseStatus();
    message.code = object.code ?? 0;
    message.error = (object.error !== undefined && object.error !== null) ? Error.fromPartial(object.error) : undefined;
    return message;
  },
};

function createBaseEmptyResponse(): EmptyResponse {
  return { status: undefined };
}

export const EmptyResponse: MessageFns<EmptyResponse> = {
  encode(message: EmptyResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.status !== undefined) {
      ResponseStatus.encode(message.status, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): EmptyResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEmptyResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.status = ResponseStatus.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): EmptyResponse {
    return { status: isSet(object.status) ? ResponseStatus.fromJSON(object.status) : undefined };
  },

  toJSON(message: EmptyResponse): unknown {
    const obj: any = {};
    if (message.status !== undefined) {
      obj.status = ResponseStatus.toJSON(message.status);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<EmptyResponse>, I>>(base?: I): EmptyResponse {
    return EmptyResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<EmptyResponse>, I>>(object: I): EmptyResponse {
    const message = createBaseEmptyResponse();
    message.status = (object.status !== undefined && object.status !== null)
      ? ResponseStatus.fromPartial(object.status)
      : undefined;
    return message;
  },
};

function createBaseByIdRequest(): ByIdRequest {
  return { id: "" };
}

export const ByIdRequest: MessageFns<ByIdRequest> = {
  encode(message: ByIdRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ByIdRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseByIdRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ByIdRequest {
    return { id: isSet(object.id) ? globalThis.String(object.id) : "" };
  },

  toJSON(message: ByIdRequest): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ByIdRequest>, I>>(base?: I): ByIdRequest {
    return ByIdRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ByIdRequest>, I>>(object: I): ByIdRequest {
    const message = createBaseByIdRequest();
    message.id = object.id ?? "";
    return message;
  },
};

function createBaseEmptyRequest(): EmptyRequest {
  return {};
}

export const EmptyRequest: MessageFns<EmptyRequest> = {
  encode(_: EmptyRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): EmptyRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEmptyRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): EmptyRequest {
    return {};
  },

  toJSON(_: EmptyRequest): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<EmptyRequest>, I>>(base?: I): EmptyRequest {
    return EmptyRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<EmptyRequest>, I>>(_: I): EmptyRequest {
    const message = createBaseEmptyRequest();
    return message;
  },
};

function createBasePaginateRequest(): PaginateRequest {
  return { page: 0, perPage: 0, fulltextSearch: undefined };
}

export const PaginateRequest: MessageFns<PaginateRequest> = {
  encode(message: PaginateRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.page !== 0) {
      writer.uint32(8).int32(message.page);
    }
    if (message.perPage !== 0) {
      writer.uint32(16).int32(message.perPage);
    }
    if (message.fulltextSearch !== undefined) {
      writer.uint32(26).string(message.fulltextSearch);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PaginateRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePaginateRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.page = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.perPage = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.fulltextSearch = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): PaginateRequest {
    return {
      page: isSet(object.page) ? globalThis.Number(object.page) : 0,
      perPage: isSet(object.perPage) ? globalThis.Number(object.perPage) : 0,
      fulltextSearch: isSet(object.fulltextSearch) ? globalThis.String(object.fulltextSearch) : undefined,
    };
  },

  toJSON(message: PaginateRequest): unknown {
    const obj: any = {};
    if (message.page !== 0) {
      obj.page = Math.round(message.page);
    }
    if (message.perPage !== 0) {
      obj.perPage = Math.round(message.perPage);
    }
    if (message.fulltextSearch !== undefined) {
      obj.fulltextSearch = message.fulltextSearch;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PaginateRequest>, I>>(base?: I): PaginateRequest {
    return PaginateRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PaginateRequest>, I>>(object: I): PaginateRequest {
    const message = createBasePaginateRequest();
    message.page = object.page ?? 0;
    message.perPage = object.perPage ?? 0;
    message.fulltextSearch = object.fulltextSearch ?? undefined;
    return message;
  },
};

function createBasePaginationMetaResult(): PaginationMetaResult {
  return { recordsTotal: 0, recordsFiltered: 0 };
}

export const PaginationMetaResult: MessageFns<PaginationMetaResult> = {
  encode(message: PaginationMetaResult, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.recordsTotal !== 0) {
      writer.uint32(8).int32(message.recordsTotal);
    }
    if (message.recordsFiltered !== 0) {
      writer.uint32(16).int32(message.recordsFiltered);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PaginationMetaResult {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePaginationMetaResult();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.recordsTotal = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.recordsFiltered = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): PaginationMetaResult {
    return {
      recordsTotal: isSet(object.recordsTotal) ? globalThis.Number(object.recordsTotal) : 0,
      recordsFiltered: isSet(object.recordsFiltered) ? globalThis.Number(object.recordsFiltered) : 0,
    };
  },

  toJSON(message: PaginationMetaResult): unknown {
    const obj: any = {};
    if (message.recordsTotal !== 0) {
      obj.recordsTotal = Math.round(message.recordsTotal);
    }
    if (message.recordsFiltered !== 0) {
      obj.recordsFiltered = Math.round(message.recordsFiltered);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PaginationMetaResult>, I>>(base?: I): PaginationMetaResult {
    return PaginationMetaResult.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PaginationMetaResult>, I>>(object: I): PaginationMetaResult {
    const message = createBasePaginationMetaResult();
    message.recordsTotal = object.recordsTotal ?? 0;
    message.recordsFiltered = object.recordsFiltered ?? 0;
    return message;
  },
};

function createBaseUserDto(): UserDto {
  return { id: "", username: "", age: 0, type: 0 };
}

export const UserDto: MessageFns<UserDto> = {
  encode(message: UserDto, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.username !== "") {
      writer.uint32(18).string(message.username);
    }
    if (message.age !== 0) {
      writer.uint32(24).int32(message.age);
    }
    if (message.type !== 0) {
      writer.uint32(32).int32(message.type);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UserDto {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUserDto();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.username = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.age = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.type = reader.int32() as any;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UserDto {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      username: isSet(object.username) ? globalThis.String(object.username) : "",
      age: isSet(object.age) ? globalThis.Number(object.age) : 0,
      type: isSet(object.type) ? userTypeFromJSON(object.type) : 0,
    };
  },

  toJSON(message: UserDto): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.username !== "") {
      obj.username = message.username;
    }
    if (message.age !== 0) {
      obj.age = Math.round(message.age);
    }
    if (message.type !== 0) {
      obj.type = userTypeToJSON(message.type);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UserDto>, I>>(base?: I): UserDto {
    return UserDto.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UserDto>, I>>(object: I): UserDto {
    const message = createBaseUserDto();
    message.id = object.id ?? "";
    message.username = object.username ?? "";
    message.age = object.age ?? 0;
    message.type = object.type ?? 0;
    return message;
  },
};

function createBaseTicket(): Ticket {
  return { id: "", ticketNumber: 0, user: undefined, session: undefined };
}

export const Ticket: MessageFns<Ticket> = {
  encode(message: Ticket, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.ticketNumber !== 0) {
      writer.uint32(16).int32(message.ticketNumber);
    }
    if (message.user !== undefined) {
      UserDto.encode(message.user, writer.uint32(26).fork()).join();
    }
    if (message.session !== undefined) {
      SessionDto.encode(message.session, writer.uint32(34).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Ticket {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTicket();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.ticketNumber = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.user = UserDto.decode(reader, reader.uint32());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.session = SessionDto.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Ticket {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      ticketNumber: isSet(object.ticketNumber) ? globalThis.Number(object.ticketNumber) : 0,
      user: isSet(object.user) ? UserDto.fromJSON(object.user) : undefined,
      session: isSet(object.session) ? SessionDto.fromJSON(object.session) : undefined,
    };
  },

  toJSON(message: Ticket): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.ticketNumber !== 0) {
      obj.ticketNumber = Math.round(message.ticketNumber);
    }
    if (message.user !== undefined) {
      obj.user = UserDto.toJSON(message.user);
    }
    if (message.session !== undefined) {
      obj.session = SessionDto.toJSON(message.session);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Ticket>, I>>(base?: I): Ticket {
    return Ticket.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Ticket>, I>>(object: I): Ticket {
    const message = createBaseTicket();
    message.id = object.id ?? "";
    message.ticketNumber = object.ticketNumber ?? 0;
    message.user = (object.user !== undefined && object.user !== null) ? UserDto.fromPartial(object.user) : undefined;
    message.session = (object.session !== undefined && object.session !== null)
      ? SessionDto.fromPartial(object.session)
      : undefined;
    return message;
  },
};

function createBaseSessionDto(): SessionDto {
  return { id: "", date: "", timeSlot: 0, roomNumber: 0, tickets: [] };
}

export const SessionDto: MessageFns<SessionDto> = {
  encode(message: SessionDto, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.date !== "") {
      writer.uint32(18).string(message.date);
    }
    if (message.timeSlot !== 0) {
      writer.uint32(24).int32(message.timeSlot);
    }
    if (message.roomNumber !== 0) {
      writer.uint32(32).int32(message.roomNumber);
    }
    for (const v of message.tickets) {
      Ticket.encode(v!, writer.uint32(42).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SessionDto {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSessionDto();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.date = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.timeSlot = reader.int32() as any;
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.roomNumber = reader.int32();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.tickets.push(Ticket.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SessionDto {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      date: isSet(object.date) ? globalThis.String(object.date) : "",
      timeSlot: isSet(object.timeSlot) ? timeSlotFromJSON(object.timeSlot) : 0,
      roomNumber: isSet(object.roomNumber) ? globalThis.Number(object.roomNumber) : 0,
      tickets: globalThis.Array.isArray(object?.tickets) ? object.tickets.map((e: any) => Ticket.fromJSON(e)) : [],
    };
  },

  toJSON(message: SessionDto): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.date !== "") {
      obj.date = message.date;
    }
    if (message.timeSlot !== 0) {
      obj.timeSlot = timeSlotToJSON(message.timeSlot);
    }
    if (message.roomNumber !== 0) {
      obj.roomNumber = Math.round(message.roomNumber);
    }
    if (message.tickets?.length) {
      obj.tickets = message.tickets.map((e) => Ticket.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SessionDto>, I>>(base?: I): SessionDto {
    return SessionDto.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SessionDto>, I>>(object: I): SessionDto {
    const message = createBaseSessionDto();
    message.id = object.id ?? "";
    message.date = object.date ?? "";
    message.timeSlot = object.timeSlot ?? 0;
    message.roomNumber = object.roomNumber ?? 0;
    message.tickets = object.tickets?.map((e) => Ticket.fromPartial(e)) || [];
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
