// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.2.5
//   protoc               v5.28.2
// source: manager_messages.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { TimeSlot, timeSlotFromJSON, timeSlotToJSON } from "./general";

export const protobufPackage = "manager";

export interface AddMovieRequest {
  name: string;
  ageRestriction: number;
  writer: string;
  sessions: UpsertSessionDto[];
}

export interface UpsertSessionDto {
  roomNumber: string;
  dates: SessionDatesDto[];
}

export interface SessionDatesDto {
  date: string;
  timeSlots: TimeSlot[];
}

export interface UpdateMovieRequest {
  id: string;
  name?: string | undefined;
  ageRestriction?: number | undefined;
  writer?: string | undefined;
  sessions: UpsertSessionDto[];
}

function createBaseAddMovieRequest(): AddMovieRequest {
  return { name: "", ageRestriction: 0, writer: "", sessions: [] };
}

export const AddMovieRequest: MessageFns<AddMovieRequest> = {
  encode(message: AddMovieRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.name !== "") {
      writer.uint32(10).string(message.name);
    }
    if (message.ageRestriction !== 0) {
      writer.uint32(16).int32(message.ageRestriction);
    }
    if (message.writer !== "") {
      writer.uint32(26).string(message.writer);
    }
    for (const v of message.sessions) {
      UpsertSessionDto.encode(v!, writer.uint32(34).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AddMovieRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAddMovieRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.ageRestriction = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.writer = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.sessions.push(UpsertSessionDto.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AddMovieRequest {
    return {
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      ageRestriction: isSet(object.ageRestriction) ? globalThis.Number(object.ageRestriction) : 0,
      writer: isSet(object.writer) ? globalThis.String(object.writer) : "",
      sessions: globalThis.Array.isArray(object?.sessions)
        ? object.sessions.map((e: any) => UpsertSessionDto.fromJSON(e))
        : [],
    };
  },

  toJSON(message: AddMovieRequest): unknown {
    const obj: any = {};
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.ageRestriction !== 0) {
      obj.ageRestriction = Math.round(message.ageRestriction);
    }
    if (message.writer !== "") {
      obj.writer = message.writer;
    }
    if (message.sessions?.length) {
      obj.sessions = message.sessions.map((e) => UpsertSessionDto.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AddMovieRequest>, I>>(base?: I): AddMovieRequest {
    return AddMovieRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AddMovieRequest>, I>>(object: I): AddMovieRequest {
    const message = createBaseAddMovieRequest();
    message.name = object.name ?? "";
    message.ageRestriction = object.ageRestriction ?? 0;
    message.writer = object.writer ?? "";
    message.sessions = object.sessions?.map((e) => UpsertSessionDto.fromPartial(e)) || [];
    return message;
  },
};

function createBaseUpsertSessionDto(): UpsertSessionDto {
  return { roomNumber: "", dates: [] };
}

export const UpsertSessionDto: MessageFns<UpsertSessionDto> = {
  encode(message: UpsertSessionDto, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.roomNumber !== "") {
      writer.uint32(10).string(message.roomNumber);
    }
    for (const v of message.dates) {
      SessionDatesDto.encode(v!, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UpsertSessionDto {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUpsertSessionDto();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.roomNumber = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.dates.push(SessionDatesDto.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UpsertSessionDto {
    return {
      roomNumber: isSet(object.roomNumber) ? globalThis.String(object.roomNumber) : "",
      dates: globalThis.Array.isArray(object?.dates) ? object.dates.map((e: any) => SessionDatesDto.fromJSON(e)) : [],
    };
  },

  toJSON(message: UpsertSessionDto): unknown {
    const obj: any = {};
    if (message.roomNumber !== "") {
      obj.roomNumber = message.roomNumber;
    }
    if (message.dates?.length) {
      obj.dates = message.dates.map((e) => SessionDatesDto.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UpsertSessionDto>, I>>(base?: I): UpsertSessionDto {
    return UpsertSessionDto.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UpsertSessionDto>, I>>(object: I): UpsertSessionDto {
    const message = createBaseUpsertSessionDto();
    message.roomNumber = object.roomNumber ?? "";
    message.dates = object.dates?.map((e) => SessionDatesDto.fromPartial(e)) || [];
    return message;
  },
};

function createBaseSessionDatesDto(): SessionDatesDto {
  return { date: "", timeSlots: [] };
}

export const SessionDatesDto: MessageFns<SessionDatesDto> = {
  encode(message: SessionDatesDto, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.date !== "") {
      writer.uint32(18).string(message.date);
    }
    writer.uint32(26).fork();
    for (const v of message.timeSlots) {
      writer.int32(v);
    }
    writer.join();
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SessionDatesDto {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSessionDatesDto();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.date = reader.string();
          continue;
        }
        case 3: {
          if (tag === 24) {
            message.timeSlots.push(reader.int32() as any);

            continue;
          }

          if (tag === 26) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.timeSlots.push(reader.int32() as any);
            }

            continue;
          }

          break;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SessionDatesDto {
    return {
      date: isSet(object.date) ? globalThis.String(object.date) : "",
      timeSlots: globalThis.Array.isArray(object?.timeSlots)
        ? object.timeSlots.map((e: any) => timeSlotFromJSON(e))
        : [],
    };
  },

  toJSON(message: SessionDatesDto): unknown {
    const obj: any = {};
    if (message.date !== "") {
      obj.date = message.date;
    }
    if (message.timeSlots?.length) {
      obj.timeSlots = message.timeSlots.map((e) => timeSlotToJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SessionDatesDto>, I>>(base?: I): SessionDatesDto {
    return SessionDatesDto.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SessionDatesDto>, I>>(object: I): SessionDatesDto {
    const message = createBaseSessionDatesDto();
    message.date = object.date ?? "";
    message.timeSlots = object.timeSlots?.map((e) => e) || [];
    return message;
  },
};

function createBaseUpdateMovieRequest(): UpdateMovieRequest {
  return { id: "", name: undefined, ageRestriction: undefined, writer: undefined, sessions: [] };
}

export const UpdateMovieRequest: MessageFns<UpdateMovieRequest> = {
  encode(message: UpdateMovieRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.name !== undefined) {
      writer.uint32(18).string(message.name);
    }
    if (message.ageRestriction !== undefined) {
      writer.uint32(24).int32(message.ageRestriction);
    }
    if (message.writer !== undefined) {
      writer.uint32(34).string(message.writer);
    }
    for (const v of message.sessions) {
      UpsertSessionDto.encode(v!, writer.uint32(42).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UpdateMovieRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUpdateMovieRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.ageRestriction = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.writer = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.sessions.push(UpsertSessionDto.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UpdateMovieRequest {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      name: isSet(object.name) ? globalThis.String(object.name) : undefined,
      ageRestriction: isSet(object.ageRestriction) ? globalThis.Number(object.ageRestriction) : undefined,
      writer: isSet(object.writer) ? globalThis.String(object.writer) : undefined,
      sessions: globalThis.Array.isArray(object?.sessions)
        ? object.sessions.map((e: any) => UpsertSessionDto.fromJSON(e))
        : [],
    };
  },

  toJSON(message: UpdateMovieRequest): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.name !== undefined) {
      obj.name = message.name;
    }
    if (message.ageRestriction !== undefined) {
      obj.ageRestriction = Math.round(message.ageRestriction);
    }
    if (message.writer !== undefined) {
      obj.writer = message.writer;
    }
    if (message.sessions?.length) {
      obj.sessions = message.sessions.map((e) => UpsertSessionDto.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UpdateMovieRequest>, I>>(base?: I): UpdateMovieRequest {
    return UpdateMovieRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UpdateMovieRequest>, I>>(object: I): UpdateMovieRequest {
    const message = createBaseUpdateMovieRequest();
    message.id = object.id ?? "";
    message.name = object.name ?? undefined;
    message.ageRestriction = object.ageRestriction ?? undefined;
    message.writer = object.writer ?? undefined;
    message.sessions = object.sessions?.map((e) => UpsertSessionDto.fromPartial(e)) || [];
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
