// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.2.5
//   protoc               v5.28.2
// source: services.proto

/* eslint-disable */
import { BuyTicketResponse, ViewWatchHistoryResponse, WatchMovieResponse } from "./customer_messages";
import { ByIdRequest, EmptyResponse, PaginateRequest } from "./general";
import { AddMoviesRequest, UpdateMovieRequest } from "./manager_messages";
import { ListMoviesResponse, LoginRequest, LoginResponse, RegisterRequest, RegisterResponse } from "./user_messages";

export const protobufPackage = "micro.v1.portfolio";

export interface PCustomerService {
  buyTicket(request: ByIdRequest): Promise<BuyTicketResponse>;
  watchMovie(request: ByIdRequest): Promise<WatchMovieResponse>;
  viewWatchHistory(request: PaginateRequest): Promise<ViewWatchHistoryResponse>;
}

export interface PUserService {
  listMovies(request: PaginateRequest): Promise<ListMoviesResponse>;
  register(request: RegisterRequest): Promise<RegisterResponse>;
  login(request: LoginRequest): Promise<LoginResponse>;
  delete(request: ByIdRequest): Promise<EmptyResponse>;
}

export interface PManagerService {
  createMovies(request: AddMoviesRequest): Promise<EmptyResponse>;
  updateMovies(request: UpdateMovieRequest): Promise<EmptyResponse>;
  deleteMovies(request: ByIdRequest): Promise<EmptyResponse>;
}
